/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ChecklistItem = IDL.Record({
  'id' : IDL.Nat,
  'isChecked' : IDL.Bool,
  'order' : IDL.Nat,
  'text' : IDL.Text,
});
export const Schedule = IDL.Record({
  'departureTime' : IDL.Text,
  'isEnabled' : IDL.Bool,
  'destinationLabel' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addItem' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getItems' : IDL.Func([], [IDL.Vec(ChecklistItem)], ['query']),
  'getLockerStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getSchedule' : IDL.Func([], [IDL.Opt(Schedule)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'lockLocker' : IDL.Func([], [], []),
  'removeItem' : IDL.Func([IDL.Nat], [], []),
  'resetAllChecks' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSchedule' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  'toggleItem' : IDL.Func([IDL.Nat], [], []),
  'unlockLocker' : IDL.Func([], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ChecklistItem = IDL.Record({
    'id' : IDL.Nat,
    'isChecked' : IDL.Bool,
    'order' : IDL.Nat,
    'text' : IDL.Text,
  });
  const Schedule = IDL.Record({
    'departureTime' : IDL.Text,
    'isEnabled' : IDL.Bool,
    'destinationLabel' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addItem' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getItems' : IDL.Func([], [IDL.Vec(ChecklistItem)], ['query']),
    'getLockerStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getSchedule' : IDL.Func([], [IDL.Opt(Schedule)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'lockLocker' : IDL.Func([], [], []),
    'removeItem' : IDL.Func([IDL.Nat], [], []),
    'resetAllChecks' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSchedule' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
    'toggleItem' : IDL.Func([IDL.Nat], [], []),
    'unlockLocker' : IDL.Func([], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };