/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChecklistItem {
  'id' : bigint,
  'isChecked' : boolean,
  'order' : bigint,
  'text' : string,
}
export interface Schedule {
  'departureTime' : string,
  'isEnabled' : boolean,
  'destinationLabel' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addItem' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getItems' : ActorMethod<[], Array<ChecklistItem>>,
  'getLockerStatus' : ActorMethod<[], boolean>,
  'getSchedule' : ActorMethod<[], [] | [Schedule]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'lockLocker' : ActorMethod<[], undefined>,
  'removeItem' : ActorMethod<[bigint], undefined>,
  'resetAllChecks' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSchedule' : ActorMethod<[string, string, boolean], undefined>,
  'toggleItem' : ActorMethod<[bigint], undefined>,
  'unlockLocker' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];